use_frameworks!

platform :ios, '8.0'

target 'MyRootOutSource_Example' do
  pod 'MyRootOutSource', :path => '../'

  target 'MyRootOutSource_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
